import React, { useEffect } from 'react'

import './Info.css'

export default function InfoPage() {
  useEffect(() => {
    document.body.classList.add('info-body')

    return () => document.body.classList.remove('info-body')
  })
  return (
    <div className="info-container">
      <h1 className="info-title">Info</h1>
      <p align="justify">
        Cloud computing permits customers to store their data in a remote
        location. However, data security is the most significant risk in cloud
        computing. Due to this, many businesses are hesitant to use cloud
        environments. To combat this, a CSP's Service-Level Agreement (SLA) with
        its customers should include provisions for 14 confidentiality,
        integrity, and availability. If not, verify that important information
        is not stored in a public cloud, and if it is, that it is encrypted.
        Effective auditing procedures may also be utilized to ensure data
        integrity.
      </p>
      <p align="justify">
        However, other than changing the system of the database, there are
        certain ways as to how companies that offer these services could
        strengthen their security. Hao, Y., et al (2021), proposed that DNA
        could be used in order to increase the effectiveness of security in
        databases. Although data storage has been increasing in innovations and
        developments, it would still be useless if there would not be an
        increase in innovation when it comes to the security and access to these
        data. Moreover, it was found in the study that some research based on
        bimolecular reactions has been done on the topic of ensuring the
        confidentiality, integrity, and availability (CIA) of information that
        has been saved. In addition, the development of interfaces between in
        vitro and in vivo systems has the potential to broaden the uses of
        DNA-based information storage and to raise the level of intelligence of
        synthetic biological systems. Zhe, D., et al. (2017) argues that
        technologies such as identity authentication, access control, and
        transmission encryption can be utilized to guarantee the security of the
        cloud storage system. Verifying the user's identity is the initial step
        in the process. To achieve mutual authentication between the user and
        the cloud storage server, for example, utilize the identity
        authentication approach provided by the cloud terminal. Encrypting the
        data transmission in order to accomplish end-to-end data transmission is
        the second step in the process. During transmission, data is protected
        from any potential security risks thanks to this measure. The third
        step, which is to implement access control to prevent illegal access to
        user data, has as its primary objective the protection of user benefits.
      </p>
      <p align="justify">
        Big data is currently increasing and rapidly growing in number wherein
        businesses, organizations, cities and people are always storing their
        data in storage clouds. However, in the area where the researchers would
        be implementing the project, they lack a proper or stable area to store
        the information they have. Specifically, this project is subjected to
        Barangay 10 of Poblacion Sabang, Lipa City’s barangay office. The office
        does not have enough space to store the video records generated by the
        CCTV system such as criminal records which makes them lose track of
        people who are 17 a danger to the area. Thus, if this could be helped
        through using cloud storage, then there would possibly be a reduced rate
        and number of crimes around the area. Moreover, as discussed in the
        review of related literature and related systems, there were numerous
        studies regarding how successful cloud storage is to handle big data and
        how the security measures should be increased due to the threat patterns
        of having cloud storage. Additionally, backing systems should also be
        considered and installed due to unforeseen and unpredictable
        circumstances that are brought by using cloud storage. However, this
        would be better than having disorganized information in a room where it
        would be extremely difficult to find important information needed.
      </p>
      <br />
      <br />
      <br />
    </div>
  )
}
